name: feature-nodejs-pipeline
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Please enter SHA code"
        required: true
        type: string
      environment:
        description: "Please select environment"
        type: choice
        options:
          - qa
          - uat
          - sit
        required: true
        default: uat
permissions:
  contents: read
  statuses: write
jobs:
  non-prod-pipeline:
    if: github.ref == 'refs/heads/main'
    uses: heman-devops/workflows/.github/workflows/non-prod-pipeline.yaml@main
    with:
      version: ${{ inputs.version }}
      environment: ${{ inputs.environment }}
    secrets: inherit